### PR TITLE
Update to latest labelgun (6.1.0)

### PR DESCRIPTION
**Pull request by JamesLMilner**
I wasn't sure if the example was supposed to have labels? I couldn't see any and there was nothing obvious in the code so I assume not. Maybe worth you taking a look?

### CODE REVIEW

**Comment by ahocevar** [comment]
Sorry, but it seems the update breaks something. You can see the labels when you zoom in on the example map. But not after the update unfortunately.

**Comment by JamesLMilner** [comment]
Hey @ahocevar thanks for the feedback. I see what the problem is now. I've fixed it :) Let me know your thoughts

**Comment by ahocevar** [comment]
Hm. The labels do work now, but I tried v6.0.0 with the [ol-mapbox-style](https://npmjs.com/package/ol-mapbox-style] package and the `mapbox.html` example there, and the labels are very unstable (i.e. change during panning). Looks like the extra call to `update()` rearranges things in a non-deterministic manner. Previously, I enforced getting the same labels by taking care of the order I add labels to labelgun, and not running `update()`.

**Comment by ahocevar** [comment]
Same with v6.1.0. I tried to not reset the weight, which is the z-index (i.e. I removed [this line](https://github.com/boundlessgeo/mapbox-to-ol-style/blob/v3.1.7/index.js#L728)), but still worse than with labelgun v1.0.0.

**Comment by JamesLMilner** [comment]
Hey @ahocevar thanks for your feedback. I have changed the compare function to remove the distance calculations as this causes the visual artefact's you were observing in the ol-mapbox-style example. This makes it deterministic but also more efficient as comparisons are simpler. See this gif:
labelgun-mb2ol-2

**Comment by ahocevar** [comment]
Looks great now, thanks!

**Pull request merged**
